// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   uuid.UUID   `json:"id"`
	Name string      `json:"name"`
	Bio  pgtype.Text `json:"bio"`
}

type Book struct {
	ID            uuid.UUID   `json:"id"`
	Title         string      `json:"title"`
	AuthorID      uuid.UUID   `json:"author_id"`
	PublishedYear pgtype.Int4 `json:"published_year"`
}
